import IISAvtomatizaciya_prodazhiОрганизацииEController from '../i-i-s-avtomatizaciya-prodazhi-организации-e';

var IISAvtomatizaciya_prodazhiОрганизацииENewController = IISAvtomatizaciya_prodazhiОрганизацииEController;
export default IISAvtomatizaciya_prodazhiОрганизацииENewController;
