import IISAvtomatizaciya_prodazhiОстатНаСкладEController from '../i-i-s-avtomatizaciya-prodazhi-остат-на-склад-e';

var IISAvtomatizaciya_prodazhiОстатНаСкладENewController = IISAvtomatizaciya_prodazhiОстатНаСкладEController;
export default IISAvtomatizaciya_prodazhiОстатНаСкладENewController;
